# Generated by Django 2.2.5 on 2019-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compinfractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('speed_limit', models.IntegerField()),
                ('infractions_speed', models.IntegerField()),
            ],
        ),
    ]
